name: 'Lint and Auto-Fix Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint and Auto-Fix Python Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 autopep8

    - name: Run Linter and Auto-Fix
      run: |
        # Run Flake8 to find issues
        find . -name "*.py" -exec flake8 {} +
        # Auto-fix Python files using autopep8
        find . -name "*.py" -exec autopep8 --in-place --aggressive --aggressive {} +
        echo "Linted and auto-fixed all Python files successfully"

  lint_js:
    name: Lint and Auto-Fix JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install ESLint
      run: |
        npm install -g eslint
        eslint --init

    - name: Run Linter and Auto-Fix
      run: |
        # Run ESLint to find issues and auto-fix
        find . -name "*.js" -exec eslint --fix {} +
        echo "Linted and auto-fixed all JavaScript files successfully"
